### PR TITLE
Format the code with prettier

### PR DESCRIPTION
**Pull request by gustavnikolaj**
Using Sune's [eslint-config-pretty-standard](https://github.com/sunesimonsen/eslint-config-pretty-standard) setup to continue linting for all the non-stylistic rules with standard.

What do you think? :)

### CODE REVIEW

**Comment by papandreou** [comment]
Looks great :)

https://www.youtube.com/watch?v=qFGDCxKfBUY

**Review by papandreou — APPROVED** [review]
Looks like eslint-plugin-standard doesn't support node.js 4.2, but you can just remove that from .travis.yml

:+1:

**Comment by gustavnikolaj** [comment]
Yeah, I was struggling a bit with that. I'll move to testing on 6 and 8 :-)

**Review by birkestroem — APPROVED** [review]
LGTM.

**Pull request merged**
